//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesAjaxJqueryInsertUpdate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEmployee
    {
        public int EmployeeId { get; set; }
        [Required(ErrorMessage ="This feild is required") ]
        public string Name { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public string Position { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public string Office { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public Nullable<int> Salary { get; set; }
    }
}
